### ISSUE TITLE
Pupil Invisible gaze data intersample interval - buffer?

### ISSUE THREAD

**Issue by bhouDTU** [pupil-labs/pi_preview#4]
Hi, 

I have a question about the intersample interval (isi) of the recorded gaze data from Pupil Invisible. Apologies if this is the wrong repo to raise the issue, I searched around in your repos and thought here is probably my best bet.

I recorded using Pupil Invisible and downloaded the data for analysis. I calculated the isi for the gaze data by doing `np.diff(GazeTime)`, where `GazeTime` is 'gaze ps1.time'.  Similarly for the right eye camera, `np.diff(REyeTime)`, where `REyeTime` is 'PI right v1 ps1.time'.

Here attached the histograms (log scaled) for the isi of gaze and right eye timestamps. It seems there are many peaks in the gaze isi histogram, could it be caused by buffer size during data saving? Compared to the right eye's isi histogram, which has just two main peaks, which is what we may expect from eye tracking devices. 

Is there anyway to make adjustment so that the isi of the gaze data is more stable?

Thank you very much for your help. 

Kind regards,
James
<img width="417" alt="Screenshot 2021-06-30 at 08 01 51" src="https://user-images.githubusercontent.com/72058221/123912466-5b401d80-d97d-11eb-87c0-a4b7e7b5b0cb.png">

**Comment by papr** [comment]
Hi,

I am not sure what you mean by buffer in this case. But please see me notes below:
- nanosecond to second conversion - it is important to calculate the time difference in nanoseconds and not in seconds, otherwise you loose precision during the conversion
- isi range - Gaze is estimated at the highest possible speed. This is limited by the phones computational capacity. You can get up to 66Hz in real time. The video is recorded at the full camera frame rate, i.e. 200 Hz. This is why you see different isi ranges here
- number of peaks - you get multiple peaks as an effect of dropped frames/samples
- General questions - If you have general questions instead of anything repo-specific, feel free to ask them on our Discord server https://pupil-labs.com/chat

Best,
Pablo
